[Refactor] swa-tracker-wrapper
SAP/yeoman-ui pull request #352
Opened 2020-08-26 15:07 UTC by tomer-epstein

2020-08-26 15:42 UTC, slavik-lvovsky approved these changes

2020-08-26 17:20 UTC, tomer-epstein commented
@ira-gordin-sap appreciate if you can test that it works as expected.

2020-08-27 10:16 UTC, ira-gordin-sap requested changes

2020-08-27 10:16 UTC, ira-gordin-sap commented
> @ira-gordin-sap appreciate if you can test that it works as expected.

done - works

2020-08-27 10:25 UTC, ira-gordin-sap commented on backend/src/swa-tracker/swa-tracker-wrapper.ts
> +
If you agree, I can push this change.

2020-08-27 10:48 UTC, ira-gordin-sap requested changes

2020-08-27 10:48 UTC, ira-gordin-sap commented on backend/src/swa-tracker/swa-tracker-wrapper.ts
>  const ERROR_ANALYTICS_TRACKER_NOT_INITIALIZED = 'Analytics tracker has not yet been initialized!';
We can put all the constants inside the class as well.

2020-08-27 10:48 UTC, ira-gordin-sap commented on backend/src/swa-tracker/swa-tracker-wrapper.ts
> +			eventType, generatorName, startTime, customEvents});
We don't need local startTime variable.
Inside the json sent to logger: startTime: this.startTime

2020-08-27 10:48 UTC, ira-gordin-sap commented on backend/src/swa-tracker/swa-tracker-wrapper.ts
> +			{eventType, generatorName, generationTimeSec, generationTimeMilliSec, endTime, startTime, customEvents, errorMessage});
We don't need local startTime variable.
Inside the json sent to logger: startTime: this.startTime

2020-08-27 12:37 UTC, ira-gordin-sap approved these changes

2020-08-27 12:39 UTC, merged