Show "Add to Workspace" button in the "The project has been generated" message only when no one of the the workspace folders is predecessor of the project folder.
SAP/yeoman-ui pull request #369
Opened 2020-09-17 10:16 UTC by ira-gordin-sap

Show "Add to Workspace" button in the "The project has been generated" message only when no one of the the workspace folders is predecessor of the project folder.

2020-09-17 13:55 UTC, slavik-lvovsky commented
What happens when no workspace is opened ?

2020-09-17 13:56 UTC, ira-gordin-sap commented on backend/src/vscode-youi-events.ts
> +                    return ((wsFolder.uri.fsPath === targetFolderUri.fsPath) || this.isPredecessorOf(wsFolder.uri.fsPath, targetFolderUri.fsPath));
There is some scenario for this check. I don't remember. I'll try to find it.

2020-09-17 13:58 UTC, ira-gordin-sap commented on backend/src/vscode-youi-events.ts
> +                    return ((wsFolder.uri.fsPath === targetFolderUri.fsPath) || this.isPredecessorOf(wsFolder.uri.fsPath, targetFolderUri.fsPath));
This is for Windows different disks: C: and D:.

2020-09-17 13:59 UTC, ira-gordin-sap commented on backend/src/vscode-youi-events.ts
> +                    return ((wsFolder.uri.fsPath === targetFolderUri.fsPath) || this.isPredecessorOf(wsFolder.uri.fsPath, targetFolderUri.fsPath));
I'll add test for this scenario.

2020-09-17 14:05 UTC, ira-gordin-sap commented
> What happens when no workspace is opened ?

I think there is a bug here which was here before my change.
It should show the button "Add to Workspace" I think.
I'll fix it as well.

2020-09-17 14:59 UTC, ira-gordin-sap commented
> What happens when no workspace is opened ?

I fixed (removed " && workspacePath" from "if (!foundInWorkspace && workspacePath) {"), but I see this comment there: "// 2. Theia bug: vscode.workspace.workspaceFolders should not be undefined or empty".
Are you sure it is ok to fix it?

2020-09-18 07:07 UTC, tomer-epstein commented
> > What happens when no workspace is opened ?
> 
> I think there is a bug here which was here before my change.
> It should show the button "Add to Workspace" I think.
> I'll fix it as well.

There was no bug here before.

2020-09-21 07:32 UTC, slavik-lvovsky requested changes

2020-09-21 07:32 UTC, slavik-lvovsky commented on backend/src/vscode-youi-events.ts
> +        return relativePath && !_.startsWith(relativePath, '..') && !isAbsolute(relativePath);
relative is always not absolute

2020-09-21 07:43 UTC, slavik-lvovsky commented
You need to bump package.json version

2020-09-21 12:27 UTC, ira-gordin-sap commented
I  added more tests and explanations as we close with you, @slavik-lvovsky

2020-09-21 12:37 UTC, slavik-lvovsky approved these changes

2020-09-21 12:37 UTC, merged