Open workspace should only be in create project and the generic ui
SAP/yeoman-ui pull request #443
Opened 2020-12-23 08:53 UTC by NetaMolcho

2020-12-24 04:55 UTC, slavik-lvovsky requested changes
Your code looks very good.
The problem is that sub-generator can also be of project type and if the wizard runs only such sub generator your logic will not work.
Let's discuss it.

2020-12-25 19:09 UTC, slavik-lvovsky requested changes

2020-12-25 19:09 UTC, slavik-lvovsky commented on backend/src/youi-adapter.ts
> +          this.youiEvents.doGeneratorDone(false, (_.get(err, "message", 'Yeoman UI detected an error')), false);
Chane it to Application Wizard

2020-12-26 16:59 UTC, slavik-lvovsky commented
I have added a new command that enables running any main/sub generator

2020-12-26 17:08 UTC, slavik-lvovsky approved these changes

2020-12-26 18:11 UTC, tomer-epstein commented on backend/package.json
> +				"command": "runAnyGenerator",
runGenerator sounds better

2020-12-27 06:40 UTC, slavik-lvovsky requested changes
generator-license does not work in vscode
It fails with exception.
We need to understand why. It works in BAS
It does not relates to your PR, it is an old bug and we have to fix it.

2020-12-27 08:52 UTC, slavik-lvovsky approved these changes

2020-12-27 08:52 UTC, merged