fix: workaround for chrome issue
SAP/yeoman-ui pull request #569
Opened 2021-04-20 16:17 UTC by slavik-lvovsky

2021-04-20 16:28 UTC, ira-gordin-sap approved these changes
looks ok for me, but I am not an expert in this staff

2021-04-21 05:00 UTC, alex-gilin requested changes

2021-04-21 05:00 UTC, alex-gilin commented on packages/frontend/src/App.vue
> +    const refreshId = setInterval(() => {
please add a 'TODO' comment to remove that stuff when a root cause will solved

2021-04-21 05:00 UTC, alex-gilin commented on packages/frontend/src/ExploreGensApp.vue
> +    const refreshId = setInterval(() => {
please add a 'TODO' comment to remove that stuff when a root cause will solved

2021-04-21 06:11 UTC, alex-gilin requested changes

2021-04-21 06:11 UTC, alex-gilin commented on packages/frontend/src/utils.js
> +  removeClass: (elementId, className, interval = 100) => {
```suggestion
  removeCssClassWhenRendered: (elementId, className, interval = 100) => {
```

2021-04-21 06:11 UTC, alex-gilin commented on packages/frontend/src/App.vue
> +    utils.removeClass("workaround", "material-icons");
please consider to add a 'TODO' comment to remove that stuff when root cause will solved

2021-04-21 06:11 UTC, alex-gilin commented on packages/frontend/src/ExploreGensApp.vue
> +    utils.removeClass("workaround-ex", "material-icons");
please consider to add a 'TODO' comment to remove that stuff when root cause will solved

2021-04-21 07:26 UTC, alex-gilin approved these changes

2021-04-21 08:52 UTC, merged