feat(frontend): consumes latest inquirer-gui 0.5.0
SAP/yeoman-ui pull request #758
Opened 2023-04-17 15:16 UTC by IainSAP

- update inquirer-gui and auto-complete plugin dependencies to provide new funtionality
- adds ability to toggle busy indicator from plugins explicitly
- adds test to cover

2023-04-17 15:31 UTC, IainSAP commented on yarn.lock
> +  resolved "https://int.repositories.cloud.sap/artifactory/api/npm/build-milestones-npm/@sap/bas-sdk/-/@sap/bas-sdk-3.2.1.tgz#6e43be6162a22b1a27996d9ec06118470a526c30"
Will fix

2023-04-17 15:45 UTC, rimasirich requested changes

2023-04-17 15:45 UTC, rimasirich commented on packages/backend/package.json
> +  "version": "1.10.9",
yeoman-ui is a mono-repo where versions are bumped automatically by lerna, please, don't bump version manually

2023-04-17 15:45 UTC, rimasirich commented on packages/frontend/package.json
> +  "version": "1.10.9",
yeoman-ui is a mono-repo where versions are bumped automatically by lerna, please, don't bump version manually

2023-04-18 07:35 UTC, rimasirich approved these changes

2023-04-18 08:48 UTC, merged