feat: usage analytics report to azure application insights
SAP/yeoman-ui pull request #817
Opened 2024-02-22 13:55 UTC by veredcon

2024-02-29 09:31 UTC, alex-gilin requested changes

2024-02-29 09:31 UTC, alex-gilin commented on packages/backend/src/usage-report/usage-analytics-wrapper.ts
> +      logger.error(error);
```suggestion
      logger?.error(error);
```

2024-02-29 09:31 UTC, alex-gilin commented on packages/backend/src/usage-report/usage-analytics-wrapper.ts
> +      logger.error(error);
```suggestion
      logger?.error(error);
```

2024-02-29 09:31 UTC, alex-gilin commented on packages/backend/src/usage-report/usage-analytics-wrapper.ts
> +      logger?.trace("SAP Web Analytics tracker was called and start time was initialized", {
is the log text as intended - is there a case where the start time is NOT initialized?

2024-02-29 09:31 UTC, alex-gilin commented on packages/backend/.nycrc.json
> +  "statements": 92
👎

2024-02-29 12:46 UTC, veredcon commented on packages/backend/src/usage-report/usage-analytics-wrapper.ts
> +import * as path from "path";
solved together with require

2024-03-03 08:09 UTC, alex-gilin requested changes

2024-03-03 08:09 UTC, alex-gilin commented on packages/backend/webpack.config.js
> +      },
looks like added by mistake. please verify

2024-03-03 09:14 UTC, alex-gilin approved these changes

2024-03-03 09:18 UTC, merged